STUDENTS = [
    ('Abimanyu M', 'M_Abimanyu'),
    ('Adithya R', 'Adithyar001'),
    ('Aparnaa K S', 'Aparnaa27'),
    ('Arvindh Babu V', 'arvindhbabu23'),
    ('Asifa Begum M', 'Asifa18'),
    ('Balaji T', 'BALAJITAMILSELVAN'),
    ('BALAJI V M', '_balaji_vm'),
    ('Balasubasri A', 'balasubasri'),
    ('Daniel Titus T', 'danieltitus'),
    ('Deepan Raj R', 'Deepan_Raj_R'),
    ('Geethavarshini R', 'geeth_18'),
    ('Gocegin Sanjay N', 'Gocegin_sanjay'),
    ('Hariharan N N', 'Hari_Haran_2589'),
    ('Harsika S', 'harsika07'),
    ('Hishaam M', ''),
    ('Jagath P', 'jagath_0711'),
    ('Janarthan A', ''),
    ('Jayapriya S', 'Priyasakthivel'),
    ('Jeya Kartika G', 'jeykagovind'),
    ('Joshua Jenisus R', 'Jenisusjr'),
    ('Kamlesh S', 'S_Kamlesh'),
    ('Karuppanan T', 'Karuppanan_Thandapani'),
    ('Kiruthika K', 'kiruthika_0511'),
    ('Kishore A', ''),
    ('Kowsalya M', 'kows_26'),
    ('Krishnaji S', 'Skrishnaji'),
    ('Manikandan M', 'qk29BICfmQ'),
    ('Mirudhula M', 'mirudhu_12'),
    ('Mohamed Haaris S', 'MohamedHaaris'),
    ('Mohamed Hasan A', 'Abu_hasan2006'),
    ('Mohamed Idris S', 'MohamedIdris'),
    ('Mohamed Ishaaq M F', 'md_ishaaq00'),
    ('Mohamed Nifrasdeen H', 'nifras786'),
    ('Muthukumar S', 'Muthukumar-Leet'),
    ('Nagul Inban S', 'NagulInban'),
    ('Navadeep S', 'Navadeep7'),
    ('Nikshitha S', 'Nikshitha-S'),
    ('Nithish A', 'Nithish'),
    ('Nivetha R', 'Nive_20'),
    ('Nowfil A', 'Nowfil25'),
    ('Oviya M', 'Oviyamuruganantham'),
    ('Ponarunkumar A', 'Ponarunkumar'),
    ('Pooja J', 'pooja_jayaprakash27'),
    ('Priyaa Ravi', 'Priyaa_16'),
    ('Ramani Jayandren G', 'Ramani_JayandrenG'),
    ('Rasin Ahmed F', 'Rasin_ahmed_F'),
    ('Sachin R', 'rsachin_006'),
    ('Sakthi Shriram K', 'sakthi_shriram'),
    ('Sarmila R', 'sarmila_Rajarajan'),
    ('Sasikumar S', 'sasikumar_selvaraj'),
    ('Srija S', 'Srija_019'),
    ('Srinath T', 'Srinath__27'),
    ('Subhashini S S', 'subaa27'),
    ('Subitha M', 'Subitha12'),
    ('Tharun R', 'tL1eFZ6alJ'),
    ('Tharunraj R', 'Tharunraj007'),
    ('Vahies Vishwanathan P V', ''),
    ('Vijay R S', 'Vijay10'),
    ('Vishwa R', 'vishwarajarajan'),
    ('Visveshvaran M', 'VisveshvaranM'),
    ('Yogapriya V', 'Yogapriya_2004'),
    ('Yogiswaran K', 'Doz06xfcCw'),
    ('Yukesh S', 'rjtBAYLWVn'),
]
